// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAurrmAFlCjBgO--OHbh632CYD1TL9NW64',
    appId: '1:613146933640:web:efa798f19f73a5347ba23d',
    messagingSenderId: '613146933640',
    projectId: 'findmy-138d4',
    authDomain: 'findmy-138d4.firebaseapp.com',
    storageBucket: 'findmy-138d4.appspot.com',
    measurementId: 'G-7DL0276GL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKVsZLEeACYoL6kYjTJYeu0USrPA7gqNY',
    appId: '1:613146933640:android:0f39df98d8636b367ba23d',
    messagingSenderId: '613146933640',
    projectId: 'findmy-138d4',
    storageBucket: 'findmy-138d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOQvU7hYObsA1h9qKQ9qOa5Qws0bCwu28',
    appId: '1:613146933640:ios:c8e4b07ce420896d7ba23d',
    messagingSenderId: '613146933640',
    projectId: 'findmy-138d4',
    storageBucket: 'findmy-138d4.appspot.com',
    iosClientId: '613146933640-senj13tcakinoqbjgn5fu341ioor7ms6.apps.googleusercontent.com',
    iosBundleId: 'com.example.findmyjob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOQvU7hYObsA1h9qKQ9qOa5Qws0bCwu28',
    appId: '1:613146933640:ios:85df9c8afbc0d7ca7ba23d',
    messagingSenderId: '613146933640',
    projectId: 'findmy-138d4',
    storageBucket: 'findmy-138d4.appspot.com',
    iosClientId: '613146933640-249qao3r668u0hsk6ro436c3cr2ffbft.apps.googleusercontent.com',
    iosBundleId: 'com.example.findmyjob.RunnerTests',
  );
}
